# -*- coding: utf-8 -*-
"""mesa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154F-T8au9tLYptQMBgI4nocK-X3dalrf
"""

pip install mesa[rec]

# mesaパッケージ直下の属性・モジュールを表示
print(dir(mesa))

pip install seaborn

# Has multi-dimensional arrays and matrices.
# Has a large collection of mathematical functions to operate on these arrays.
import numpy as np

# Data manipulation and analysis.
import pandas as pd

# Data visualization tools.
import seaborn as sns

import mesa

from mesa.datacollection import DataCollector
import random

import random

class Post:
    def __init__(self, poster_id, quality, step):
        self.poster_id = poster_id  # 投稿者ID
        self.quality = quality
        self.step = step
        self.reactions = 0

class UserAgent:
    def __init__(self, model, agent_id):
        self.model = model
        self.agent_id = agent_id  # 識別用ID
        self.posts = []

    def step(self, current_step):
        if random.random() < 0.3:
            quality = random.uniform(0, 1)
            post = Post(self.agent_id, quality, current_step)
            self.model.posts.append(post)
            self.posts.append(post)

        for post in self.model.posts:
            if current_step - post.step > 10:
                continue
            reaction_prob = min(0.5, post.quality * 0.5)
            if random.random() < reaction_prob:
                post.reactions += 1

class UserModel:
    def __init__(self, n, seed=None):
        if seed is not None:
            random.seed(seed)
        self.num_agents = n
        self.current_step = 0
        self.agent_list = []
        self.posts = []

        for i in range(n):
            agent = UserAgent(model=self, agent_id=i)
            self.agent_list.append(agent)

    def step(self):
        for agent in self.agent_list:
            agent.step(self.current_step)
        self.current_step += 1

# 実行例
model = UserModel(10)
for _ in range(30):
    model.step()

print(f"Total posts: {len(model.posts)}")
for i, post in enumerate(model.posts):
    print(f"Post {i}: Poster {post.poster_id}, Quality {post.quality:.2f}, Step {post.step}, Reactions {post.reactions}")

